### ISSUE TITLE
Screen tearing

### ISSUE THREAD

**Issue by Marat-Tanalin** [bladeSk/DOSBox-pixel-perfect#2]
There is screen tearing all the time with _default_ settings e.g. with the “Epic Pinball” game.

Tried `output=opengl` instead of the default `output=openglnb` — same result.

`output=ddraw` was the only nonblurry `output` mode that provided no tearing, but, as expected according to the DOSBox-pp readme, it’s not a subject for pixel-perfect scaling — some pixels have different size.

Fwiw, I use a 4K monitor — Dell P2415Q.

**Comment by bladeSk** [comment]
What OS are you running?
Does switching to windowed mode eliminate the tearing?

**Comment by Marat-Tanalin** [comment]
Windows 10 1809. Switching to windowed mode seems to remove tearing (there is some periodical subtle stuttering though). But Afaict, `borderless=true` (being in the DOSBox-pp configuration by default) means that full screen is actually a window too, that just has the size of screen/desktop.

**Comment by bladeSk** [comment]
This should definitely work without tearing. Could you send me your dosbox.conf file? I'll investigate what may be causing this.

**Comment by Marat-Tanalin** [comment]
As I said, this happens with the _default_ dosbox.conf bundled with the latest release r4019.2.

Fwiw, DOSBox ECE works without tearing with the same game on the same system with [these](http://tanalin.com/en/articles/lossless-scaling/#h-partial-virtualization) settings:

```
[sdl]
fullscreen=true
output=openglpp
glfullvsync=true
```

(I’m aware that pixel-perfect patch used in DOSBox ECE and your DOSBox-pp use different incompatible settings for pixel-perfect scaling. I’m providing specific settings just for clarity.)

## Update:
My GPU is nVidia GeForce _GTX 650 Ti Boost_ with graphics driver version 419.17 (2019-02-22).

Additionally tested under Window 7 — same result.

I also noticed that if I press the <kbd>Win</kbd> key, so that the Windows taskbar and the Start menu are shown above DOSBox, there is no tearing (just some stuttering like in windowed mode). There is also short-time black background instead of DOSBox rendered image when switching between the normal full-screen state and the state when the taskbar and Start menu are shown. So it’s apparently the borderless-window mode that doesn’t work, so full-screen mode in DOSBox-pp is currently _really_ full-screen, not borderless.

**Comment by bladeSk** [comment]
Fixed in https://github.com/bladeSk/DOSBox-pixel-perfect/releases/tag/r4019.3
